---
machines:
  - name: centos7-1
    box: centos/7
    cpu: 2
    memory: 2048
    linked_clone: true
    private_ip: 192.168.56.11
    shell_script_path: provisioning/shell/default/configure.sh
    ansible_playbook_path: provisioning/ansible/default/playbook.yaml
  - name: centos7-2
    box: centos/7
    cpu: 2
    memory: 2048
    linked_clone: true
    private_ip: 192.168.56.12
    shell_script_path: provisioning/shell/default/configure.sh
    ansible_playbook_path: provisioning/ansible/default/playbook.yaml
