---
name: bionic-1
box: ubuntu/bionic64
cpu: 2
memory: 2048
private_ip: 192.168.56.11  # range: 192.168.56.0/21
shell_script_path: provisioning/shell/default/configure.sh
ansible_playbook_path: provisioning/ansible/default/playbook.yaml
